### ISSUE TITLE
https://collegescorecard.ed.gov should send the Strict-Transport-Security header

### ISSUE THREAD

**Issue by alex** [RTICWDT/college-scorecard#1296]
This ensures that a browser will never attempt to make an `http://` request in the future.

cc: @konklone

**Comment by konklone** [comment]
CloudFront and S3 make this challenging. Either S3 or CF will have to improve HSTS support, one of the two will have to be swapped out for something else, or a proxy gets put in the middle.

**Comment by barkimedes** [comment]
@alex I know this is useful, but do you know (in terms of prioritization), is this super important (like a policy compliance thing)? Or a good "right thing to do on the internet thing?

@konklone This sounds like a lot of work. Is it as much work as it sounds?

**Comment by konklone** [comment]
It is a [policy compliance thing](https://https.cio.gov), and by the letter of the rule, `collegescorecard.ed.gov` doesn't get until December 2016 to do it, because it was released after M-15-13 came out. 

However, [OMB does give two ways to accomplish it](https://https.cio.gov/guide/): 

1. Put the HSTS header on each subdomain. (Which is what @alex asked for.)
2. Put an HSTS header on the domain root (e.g. `https://ed.gov`) that include the `includeSubDomains` and `preload` flags. (Which is the best possible outcome.)

`ed.gov` has a lot of subdomains, and potentially may include intranet sites that were nonetheless made as subdomains of a public second-level domain name. I think @djharrity would have an idea about the timeline/viability of getting `ed.gov` fully HSTS preloaded.

But either way, I believe `collegescorecard.ed.gov` is hosted through Federalist at 18F? @dhcole and I are both working on ways to easily give Federalist-hosted sites easy HSTS. In either case, I hope it's not a lot of work for the College Choice team.

**Comment by djharrity** [comment]
The timeline/viability for ed.gov fully HSTS Preloaded is a significant challenge and not around the near corner. The Ed.gov has hundreds of public subdomain a hosted by a decentralized group of host providers. We are making significant progress on Always On HTTPS but HSTS will take time.

**Comment by konklone** [comment]
> We are making significant progress on Always On HTTPS but HSTS will take time.

That's what I figured (and yeah, Ed is making visibly significant progress). Hopefully this is something @dhcole and I can resolve at the hosting level, for collegescorecard.ed.gov and the other domains Federalist hosts. If not, we'll figure something else out!

**Comment by hollyallen** [comment]
@konklone @dhcole Thanks for your work on this. Do you have a Federalist ticket I can reference?

**Comment by hollyallen** [comment]
Nothing for us. Upstream ticket is: https://github.com/18F/federalist/issues/161

**Comment by brownpl** [comment]
Link to #1574

**Comment by brownpl** [comment]
With the recent Federalist migration, the strict-transport-security header is now being sent. 

<img width="604" alt="screen shot 2017-04-25 at 3 47 43 pm" src="https://cloud.githubusercontent.com/assets/1619550/25410939/90922978-29ce-11e7-897a-3d25c88c8940.png">

**Comment by konklone** [comment]
:tada: Yay for Federalist!
