### ISSUE TITLE
Data should be hosted on collegescorecard.ed.gov or other government domain

### ISSUE THREAD

**Issue by philipashlock** [RTICWDT/college-scorecard#1328]
It looks like the URLs for the [data files](https://collegescorecard.ed.gov/data/) are still using the raw aws s3 domain rather than the .gov which isn't good for permanence or authenticity

**Comment by philipashlock** [comment]
Just wanted to flag this as still being an issue and mention that OMB policy actually requires us to call out the fact that this is effectively a non-government web resource because it's not hosted on a government domain

<img width="1392" alt="screen shot 2015-10-26 at 9 30 30 am" src="https://cloud.githubusercontent.com/assets/183402/10733476/9ee9a690-7bc4-11e5-82b6-ed20c0be5347.png">


@konklone would files.18f.gov be available for this as an interim if for some reason it's not possible to host this at collegescorecard.ed.gov?

**Comment by konklone** [comment]
@philipashlock It's more of a @gbinal question at the moment as to whether files.18f.gov can be used for that, and I think it'd be an interim solution. It'd be easier if S3 let you tag usage per-sub-path rather than per-bucket, but oh well.

However, files.18f.gov was incredibly easy to set up. It's just an S3 bucket with a CloudFront distro set up in front of it. You might have to buy a cheap cert if it's for a new subdomain, in the worst case. I suggest the College Choice team set that up, and if for some reason it's impossible, talk with @gbinal and I about using files.18f.gov for this purpose.

**Comment by barkimedes** [comment]
I flagged this high-priority because I have no idea if this policy is like a "policy" or a *policy* that we totally need to comply with yesterday or something. So this should pop up towards the top in prioritization and it can be settled there.

**Comment by abisker** [comment]
@ultrasaurus once we get to this issue, would you be the right person to investigate?

**Comment by kynetiv** [comment]
I believe this has been fixed for sometime now as the data download URLs all point to a `apps.cloud.gov` address.
