### ISSUE TITLE
As a developer, I would like to use the API to get the last time the data was updated

### ISSUE THREAD

**Issue by barkimedes** [RTICWDT/college-scorecard#1359]
As a developer, I would like to use the API to find out when the last time the data was updated so that I can know if I need to download/cache more recent data.

Many users of the API will download the college data in bulk (or somehow otherwise cache the data) and then use that rather than querying the API directly all the time. But they do want to know if the data they are using is outdated. So the idea here is to provide a mechanism in the API that allows a developer to find out when the data was last updated to inform whether or not he wants to download it again.

**Comment by LisaGee** [comment]
As I think about this, knowing when the data was last updated, would be useful, not just for Developers who use the API, but also for researchers who are downloading the data from the Data section. So we should probably make a story for that use case too?

**Comment by ErieMeyer** [comment]
🇺🇸

**Comment by yozlet** [comment]
(originally posted this in #1360, but it's more relevant here)

The `data.json` endpoint (which reflects a JSON version of the `data.yml` file) _may_ be useful here. It's not currently documented. Example: https://ccapi-dev.18f.gov/v1/data.json

The most relevant field is the `version` field, which right now is a bit of a mess. It currently starts with `Aug27` because that's when we got the data dump from Ed, but followed by the ISO8601 date of the last time the file was updated. Rationalising this would save some work, especially since (AFAIK) we're going to stop using it to automatically trigger reindexing (thanks to some inbound work from @ultrasaurus). It'd definitely be worth splitting up to differentiate the age of the source data, the `data.yml` file and the index.

**Comment by ultrasaurus** [comment]
if you use the API and go to `/v1/data.json` the version has a date in it.  Updated to: `"version": "Mar2-2016-03-07-16:19-0700"`

This issue should remain open, since it would ideally be its own API.

**Comment by barkimedes** [comment]
Closing this very old issue; if the current maintainers of college scorecard wish to reopen, they can feel free to do so.

**Comment by barkimedes** [comment]
FYI, I'm planning to close this issue on September 1, 2022. I haven't worked on this project in 6 years and I can't find a different way to get this issue off of my open issues list. If you still need the issue, I'd suggest someone who still works on College Scorecard opening a new issue and referencing this one.

@alexsmithRTI -- tagging you because you're the person I see has committed to this repo recently and I suspect you'll know if this would cause any problem.

Thanks!
