### ISSUE TITLE
ENHANCEMENT: Change label to read: Average Debt of Graduates

### ISSUE THREAD

**Issue by LisaGee** [RTICWDT/college-scorecard#316]
Seems more streamlined and more understandble.

![image](https://cloud.githubusercontent.com/assets/12847090/9069753/1ebaa45c-3ab9-11e5-8ed2-427596500253.png)

**Comment by LisaGee** [comment]
Should be compared against wording that ED has requested and tested with users to have a better assessment.

**Comment by barkimedes** [comment]
@jjoteal The current text is 

Typical Total Debt
$xx,xxxx
For undergraduate borrowers who complete college

Thoughts? Still something you think should potentially change? Has there been any updates (usability testing) on this?

**Comment by jjoteal** [comment]
In usability testing, folks are generally understanding "Typical Total Debt", however some have lingering questions like "Is that the debt for all 4 years? Or, is that the debt just after 1 year?" I would recommend that we make the bottom phrase more clear. Perhaps something like "After graduating college (for undergraduates who have taken out loans)"

I'd love to be able to say "graduating" but not sure if we can for accuracy purposes. I can check with Clare on this (assigning to me for that purpose). I *do* like saying "taking out loans" though rather than "borrowers" as it is more straight-forward language.

**Comment by brownpl** [comment]
Seems like this has been in the wild for a year and can be closed.
